---
- name: Create Project
  hosts: localhost

  tasks:

    - name: Create Gitlab SCM Credential
      ansible.controller.credential:
        name: "Student Gitlab SCM PAT Credential"
        description: "Student Gitlab with Personal Token"
        state: present
        organization: Red Hat Training
        credential_type: Source Control
        inputs:
          username: student
          password: Student@123
        controller_username: admin
        controller_password: redhat
        controller_host: https://controller.lab.example.com
        validate_certs: false


    - name: Create Demo Project
      ansible.controller.project:
        name: "CH7 Demo Project"
        description: "Chapter 7 Demo Project from Gitlab"
        organization: "Red Hat Training"
        scm_update_on_launch: "no"
        scm_url: https://git.lab.example.com/student/Inv_Proj.git
        scm_type: git
        scm_branch: master
        credential: Student Gitlab SCM PAT Credential
        controller_username: admin
        controller_password: redhat
        controller_host: https://controller.lab.example.com
        validate_certs: false
        state: present

    - name: Create DO467 Inventory Demo Inv
      ansible.controller.inventory:
        name: "CH7 Demo Inventory"
        organization: "Red Hat Training"
        state: "present"
        controller_username: admin
        controller_password: redhat
        controller_host: https://controller.lab.example.com
        validate_certs: false



    - name: Create DO467 Project Inventory -  Source
      ansible.controller.inventory_source:
        name: "CH7 Demo Inventory Source"
        organization: "Red Hat Training"
        inventory: "CH7 Demo Inventory"
        source_project: "CH7 Demo Project"
        source: scm
        source_path: "inventory"
        update_on_launch: "no"
        overwrite: "yes"
        overwrite_vars: "yes"
        state: "present"
        controller_username: admin
        controller_password: redhat
        controller_host: https://controller.lab.example.com
        validate_certs: false



    - name: Initial Update DO467 Project Inventory -  Source
      ansible.controller.inventory_source_update:
        name: "CH7 Demo Inventory Source"
        organization: "Red Hat Training"
        inventory: "CH7 Demo Inventory"
        controller_username: admin
        controller_password: redhat
        controller_host: https://controller.lab.example.com
        validate_certs: false

    - name: Create Job Template
      ansible.controller.job_template:
        name: "CH7 - DO467 Demo Inventory Variables"
        description: "Demo Job for Inventory Variables"
        organization: Red Hat Training
        project: "CH7 Demo Project"
        inventory: "CH7 Demo Inventory"
        job_type: run
        playbook: "Inventory_Demo.yml"
        credential: DO467 Machine Credentials
        ask_extra_vars: "yes"
        controller_username: admin
        controller_password: redhat
        controller_host: https://controller.lab.example.com
        validate_certs: false
        state: present
